
select * from USERS;

-- 회원 테이블 
CREATE TABLE USERS (
  username VARCHAR2(255) NOT NULL,
  email VARCHAR2(255) NOT NULL,
  id VARCHAR2(255) NOT NULL,
  password VARCHAR2(255) NOT NULL,
  passwordChangeInterval NUMBER NOT NULL,
  last_password_change DATE NOT NULL,
  CONSTRAINT users_pk PRIMARY KEY (id)
);

-- 회원의 인증상태 추가 -> default값 N 
ALTER TABLE USERS ADD isVerified CHAR(1) DEFAULT 'N' NOT NULL;

-- 회원의 활성상태 추가 -> defualt값 ACTIVE
-- 회원의 비활성상태 -> INACTIVE
ALTER TABLE USERS ADD (
  status CHAR(10) DEFAULT 'ACTIVE' NOT NULL
);




CREATE TABLE tbl_board (
    bno NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title VARCHAR2(200) NOT NULL,
    content VARCHAR2(2000) NOT NULL,
    writer VARCHAR2(50) NOT NULL,
    regdate DATE DEFAULT SYSDATE,
    updatedate DATE DEFAULT SYSDATE,
    user_id VARCHAR2(255) NOT NULL,
    file VARCHAR2(255),
    CONSTRAINT fk_board_user FOREIGN KEY (user_id) REFERENCES USERS (id)
);










